# Generated by Django 2.2.17 on 2020-11-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm', '0028_rpmrepository_last_sync_repomd_cheksum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='checksum_type',
            field=models.CharField(choices=[('sha512', 'sha512'), ('sha1', 'sha1'), ('sha256', 'sha256'), ('sha224', 'sha224'), ('sha384', 'sha384'), ('md5', 'md5')], max_length=10),
        ),
        migrations.AlterField(
            model_name='rpmpublication',
            name='metadata_checksum_type',
            field=models.CharField(choices=[('sha512', 'sha512'), ('sha1', 'sha1'), ('sha256', 'sha256'), ('sha224', 'sha224'), ('sha384', 'sha384'), ('md5', 'md5')], max_length=10),
        ),
        migrations.AlterField(
            model_name='rpmpublication',
            name='package_checksum_type',
            field=models.CharField(choices=[('sha512', 'sha512'), ('sha1', 'sha1'), ('sha256', 'sha256'), ('sha224', 'sha224'), ('sha384', 'sha384'), ('md5', 'md5')], max_length=10),
        ),
    ]
